---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: Ensure curl is present (on older systems without SNI).
  package: name=curl state=present
  when: add_repository_key is failed

- name: Add Docker apt key (alternative for older systems without SNI).
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: false
  when: add_repository_key is failed

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: get docker-version from apt
  shell: apt-cache madison docker-{{ docker_edition }} | grep -P '{{ docker_version }}~{{ docker_edition }}~[^\s]*' -o
  register: apt_docker_version_register
  when: docker_version != ""
  changed_when: false

- name: set fact for docker version
  set_fact:
    docker_package_version: "={{ apt_docker_version_register.stdout_lines[0] }}"
  when: apt_docker_version_register is not skipped and apt_docker_version_register.rc == 0
